# Generated by Django 4.2.1 on 2023-09-25 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='Key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Shop key',
                'verbose_name_plural': 'Shop keys',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.FileField(blank=True, null=True, upload_to='images/shops', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'], message='Only JPEG, PNG and SVG image files are allowed.')], verbose_name='Logo')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('MODERATION', 'Moderation'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='MODERATION', max_length=255, verbose_name='Status')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='Site link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('whats_app_link', models.URLField(blank=True, null=True, verbose_name='Whats App link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone number')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Branch address',
                'verbose_name_plural': 'Branch addresses',
            },
        ),
    ]
