# Generated by Django 4.2.1 on 2023-08-21 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/shops', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'], message='Only JPEG, PNG and SVG image files are allowed.')], verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='shop',
            name='site_link',
            field=models.URLField(blank=True, null=True, verbose_name='Site link'),
        ),
        migrations.AddField(
            model_name='shop',
            name='whats_app_link',
            field=models.URLField(blank=True, null=True, verbose_name='Whats App link'),
        ),
    ]
