# Generated by Django 4.2.1 on 2023-08-21 22:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_instagram_link_shop_logo_shop_site_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone number')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Branch address',
                'verbose_name_plural': 'Branch addresses',
            },
        ),
    ]
