# Generated by Django 4.2.1 on 2023-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_branchaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner',
            new_name='user',
        ),
    ]
