# Configuration for OpenAPI Generator
npmName: typescript-axios
npmVersion: 1.0.0
generatorName: typescript-axios
inputSpec: https://shopper.kg/api/v1/swagger/
outputDir: src/shared/api/gen
supportsES6: true
withInterfaces: true
