# Generated by Django 4.2.1 on 2023-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsmspro',
            name='response',
        ),
        migrations.AddField(
            model_name='notificationsmspro',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('ERROR', 'Error')], default='PENDING', max_length=255, verbose_name='Status'),
        ),
    ]
