# Generated by Django 4.2.1 on 2023-10-06 18:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email_request',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='New email request'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_phone_request',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None, verbose_name='New phone request'),
        ),
    ]
