# Generated by Django 4.2.1 on 2023-09-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_productfavourite_productvariantimage_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='customers.customer', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to='products.product', verbose_name='Product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to='products.productvariant', verbose_name='Product')),
            ],
        ),
    ]
