# Generated by Django 4.2.1 on 2023-09-20 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BABY', 'Baby')], max_length=255), default=['MALE'], size=None, verbose_name='Preferences'),
            preserve_default=False,
        ),
    ]
