# Generated by Django 4.2.1 on 2023-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price from'),
        ),
    ]
