# Generated by Django 4.2.1 on 2023-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0004_alter_product_gender_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantimage',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is main'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantimage',
            unique_together={('variant', 'is_main')},
        ),
    ]
