# Generated by Django 4.2.1 on 2023-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariantimage_is_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='title',
            field=models.CharField(help_text='Color title', max_length=255, verbose_name='Title'),
        ),
    ]
