# Generated by Django 4.2.1 on 2023-11-03 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Value'), default=['Red'], size=None, verbose_name='Values'),
            preserve_default=False,
        ),
    ]
